import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { runHealthCheck } from "../../src/health/check.ts";
import { indexAllPath, projectJson } from "../../src/store/paths.ts";
import { withTempStore, seedEntry } from "../helpers/temp-store.ts";

test("runHealthCheck reports no_store when .priors is missing", async () => {
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), "priors-no-store-"));
  try {
    const report = await runHealthCheck(tmp);
    assert.equal(report.ok, false);
    assert.equal(report.project, null);
    assert.equal(report.issues.length, 1);
    assert.equal(report.issues[0]?.code, "no_store");
  } finally {
    await fs.rm(tmp, { recursive: true, force: true });
  }
});

test("runHealthCheck on a fresh store is healthy with empty counts", async () => {
  await withTempStore(async (root) => {
    const report = await runHealthCheck(root);
    assert.equal(report.ok, true);
    assert.ok(report.project);
    assert.equal(report.counts.active, 0);
    assert.equal(report.counts.staged, 0);
    assert.equal(
      report.issues.filter((i) => i.severity === "error").length,
      0,
    );
  });
});

test("runHealthCheck counts entries by status", async () => {
  await withTempStore(async (root, clock) => {
    await seedEntry(root, clock, {
      id: "pri-h-active",
      kind: "decision",
      claim: "Active decision.",
    });
    await seedEntry(root, clock, {
      id: "pri-h-stale",
      kind: "decision",
      claim: "Stale decision.",
      status: "stale",
      stale_reason: "no longer applicable",
    });
    await seedEntry(root, clock, {
      id: "pri-h-superseded",
      kind: "decision",
      claim: "Older decision.",
      status: "superseded",
    });
    await seedEntry(root, clock, {
      id: "pri-h-contested",
      kind: "decision",
      claim: "Contested decision.",
      status: "contested",
    });
    const report = await runHealthCheck(root);
    assert.equal(report.counts.active, 1);
    assert.equal(report.counts.stale, 1);
    assert.equal(report.counts.superseded, 1);
    assert.equal(report.counts.contested, 1);
    assert.equal(report.ok, true);
  });
});

test("runHealthCheck warns on broken relations", async () => {
  await withTempStore(async (root, clock) => {
    await seedEntry(root, clock, {
      id: "pri-h-rel",
      kind: "decision",
      claim: "Refers to a missing target.",
      relations: { supersedes: ["pri-does-not-exist"] },
    });
    const report = await runHealthCheck(root);
    const broken = report.issues.find((i) => i.code === "broken_relation");
    assert.ok(broken, "expected broken_relation issue");
    assert.equal(broken!.severity, "warning");
    assert.equal(report.ok, true);
  });
});

test("runHealthCheck flags stale entries without stale_reason", async () => {
  await withTempStore(async (root, clock) => {
    await seedEntry(root, clock, {
      id: "pri-h-bad-stale",
      kind: "decision",
      claim: "Stale without reason.",
      status: "stale",
    });
    const report = await runHealthCheck(root);
    const bad = report.issues.find((i) => i.code === "stale_without_reason");
    assert.ok(bad);
  });
});

test("runHealthCheck reports missing_index and the --fix path regenerates", async () => {
  await withTempStore(async (root, clock) => {
    await seedEntry(root, clock, {
      id: "pri-h-fix",
      kind: "decision",
      claim: "Index will be regenerated by health --fix.",
    });
    await fs.rm(indexAllPath(root));
    const before = await runHealthCheck(root);
    assert.ok(before.issues.some((i) => i.code === "missing_index"));

    await runHealthCheck(root, { fix: true });
    const after = await runHealthCheck(root);
    assert.equal(
      after.issues.filter((i) => i.code === "missing_index").length,
      0,
    );
  });
});

test("runHealthCheck reports missing project.json", async () => {
  await withTempStore(async (root) => {
    await fs.rm(projectJson(root));
    const report = await runHealthCheck(root);
    assert.equal(report.ok, false);
    assert.ok(report.issues.some((i) => i.code === "missing_project_json"));
  });
});
